<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PhngXPhng Ph ThngPhng Nht TnPhng T L_2e7638</name>
   <tag></tag>
   <elementGuidId>dd90e5e6-7573-4f68-b843-2d6fcc8700be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>623c6769-97e2-4e35-9bad-9898c15d405d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phường/XãPhường Phú ThượngPhường Nhật TânPhường Tứ LiênPhường Quảng AnPhường Xuân LaPhường Yên PhụPhường BưởiPhường Thụy Khuê</value>
      <webElementGuid>cd0ae926-f493-446d-b102-ef63aa92742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;payment row&quot;]/div[@class=&quot;payment-list row&quot;]/div[@class=&quot;payment-info col-sm-12 col-12 col-lg-5 col-xl-5&quot;]/div[@class=&quot;payment-form&quot;]/div[@class=&quot;payment-address-main&quot;]/div[@class=&quot;address-edit-select-container&quot;]/select[3]</value>
      <webElementGuid>e84ce8f2-e5f4-4dbd-b579-fff045f998bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='']</value>
      <webElementGuid>ea80e2d4-b41e-4c8f-ae9c-bdc6c288ef48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[3]/div/div[2]/div[2]/div/select[3]</value>
      <webElementGuid>c4406355-cc54-4d6d-a636-40536e13116f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ cụ thể'])[1]/following::select[3]</value>
      <webElementGuid>cf0a1ba2-d3f6-42e1-a577-8c4c0d32ec99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số điện thoại'])[1]/following::select[3]</value>
      <webElementGuid>fd6e7c9f-1c04-4564-953e-1acf0ec87a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giỏ hàng'])[1]/preceding::select[1]</value>
      <webElementGuid>ca679f28-fc4e-4b71-a108-b16da3162984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiến hành đến phương thức thanh toán'])[1]/preceding::select[1]</value>
      <webElementGuid>16e73739-45d3-4fdb-9437-58a13ebdfb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>8c21e247-1aac-43ad-9330-1673e0b7fd91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Phường/XãPhường Phú ThượngPhường Nhật TânPhường Tứ LiênPhường Quảng AnPhường Xuân LaPhường Yên PhụPhường BưởiPhường Thụy Khuê' or . = 'Phường/XãPhường Phú ThượngPhường Nhật TânPhường Tứ LiênPhường Quảng AnPhường Xuân LaPhường Yên PhụPhường BưởiPhường Thụy Khuê')]</value>
      <webElementGuid>69419faf-c45c-4fb1-9b86-846bae341262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
