<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Next_card-img-top</name>
   <tag></tag>
   <elementGuidId>9bc89253-788d-40c8-ade7-3c8c24c9a018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/a/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>09182f1b-faed-420a-b085-02ce186ffd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>f71896d3-968c-4301-bcb7-ec63553a679c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.aizalog.com/sale/attachment/e2ee43e8-f02c-440e-9d52-1aa876fafb1b</value>
      <webElementGuid>1bfa8727-9041-4dd2-81c7-0b2d05b99d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>028b44c5-a4c2-4060-9b07-d8e7dd979cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;homepage&quot;]/div[@class=&quot;homepage-list&quot;]/div[1]/div[@class=&quot;homepage-item&quot;]/div[@class=&quot;card-group&quot;]/div[@class=&quot;card-list&quot;]/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active&quot;]/div[1]/div[1]/div[@class=&quot;card&quot;]/a[1]/div[@class=&quot;img-container&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>2736d3db-906d-4747-a1c3-0cc89a567282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[3]/div/div/div/a/div[2]/img</value>
      <webElementGuid>8fcebd3a-395a-44d7-bf76-6ce3a31084b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[11]</value>
      <webElementGuid>ddad8400-99d8-42c8-a846-3de930cd6e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a/div[2]/img</value>
      <webElementGuid>1e3127fc-3aed-448e-98b1-c394bd6ed683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.aizalog.com/sale/attachment/e2ee43e8-f02c-440e-9d52-1aa876fafb1b' and @alt = 'product']</value>
      <webElementGuid>25c273d2-9218-40d9-9482-6442b521fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[4]/div/div/div/a/div[2]/img</value>
      <webElementGuid>4eeebfb2-54f0-49e5-ac35-930e958445a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[12]</value>
      <webElementGuid>a2f2a181-9191-4ba8-ad37-2f82f16c0cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a/div[2]/img</value>
      <webElementGuid>8932b3f8-3fd6-4bc2-8d8f-f9a878bed693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.aizalog.com/sale/attachment/9d8c4fe5-5dd1-4c51-89d9-dd9cbfacca19' and @alt = 'product']</value>
      <webElementGuid>92918b4d-c0bf-4468-8d8d-60aa8e1f69c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div/div/a/div[2]/img</value>
      <webElementGuid>bcabe0c6-323a-4991-89d8-8001c5b7a6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[10]</value>
      <webElementGuid>a4a153e2-e892-420e-b58e-298bf94679c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div[2]/img</value>
      <webElementGuid>b3a79d26-85db-4724-8e32-e7dcb4320f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.aizalog.com/sale/attachment/3089fcd8-3f7a-4713-afd9-594c4048ff18' and @alt = 'product']</value>
      <webElementGuid>817068be-e1c4-45e0-81e1-c4d47703c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[5]/div/div/div/a/div[2]/img</value>
      <webElementGuid>17dd29af-610a-4b1c-8d3e-7c0d8bb95acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[13]</value>
      <webElementGuid>f58433a1-ebaf-4110-9ee7-65132e199f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/a/div[2]/img</value>
      <webElementGuid>e0b21ae9-564a-4a2c-ae0a-4c95238750bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://api.aizalog.com/sale/attachment/11506b9f-f640-4c70-b4a7-9305d393c714' and @alt = 'product']</value>
      <webElementGuid>d731c2cd-a573-46c6-ba7f-38cad0d45dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[8]/div/div/div/a/div[2]/img</value>
      <webElementGuid>e7de537f-0717-4a3c-9c13-adf8ad486d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[16]</value>
      <webElementGuid>0405953c-50e0-489d-b5df-ddd6c78e57e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/a/div[2]/img</value>
      <webElementGuid>858293ff-5b31-4099-b190-2eb5b225c832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div/div/div/div/a/div[2]/img</value>
      <webElementGuid>eb5c65e5-27a6-4e1b-a6e0-6ef804cf607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[9]</value>
      <webElementGuid>82fd0c09-17d8-4c92-9148-08a8b7253945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>f9ff9ad0-0a00-45a8-95b5-5db1ce9daea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/div/div[6]/div/div/div/a/div[2]/img</value>
      <webElementGuid>4f84185a-6b67-4024-a397-f4b922fc242e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='product'])[14]</value>
      <webElementGuid>a277afc9-842c-4180-9c0a-927fbdeaa633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/a/div[2]/img</value>
      <webElementGuid>fa15c707-3cbe-436a-b6bd-0ee9a8379a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
